### Original dataset link
`https://www.yelp.com/dataset`

In [1]:
import os
import json
import gzip
import pandas as pd
from urllib.request import urlopen

In [2]:
## Download the data

## !wget http://deepyeti.ucsd.edu/jianmo/amazon/categoryFilesSmall/Grocery_and_Gourmet_Food_5.json.gz

In [2]:
# Load data

data = []
with gzip.open('Grocery_and_Gourmet_Food_5.json.gz') as f:
    for i in f:
        data.append(json.loads(i.strip()))
        
print(len(data))

1143860

In [3]:
# Load data into Pandas dataframe

df = pd.DataFrame.from_dict(data)
df.head()

,overall,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,unixReviewTime,vote,style,image
0,5.0,True,"11 19, 2014",A1QVBUH9E1V6I8,4639725183,Jamshed Mathur,No adverse comment.,Five Stars,1416355200,NaN,NaN,NaN
1,5.0,True,"10 13, 2016",A3GEOILWLK86XM,4639725183,itsjustme,Gift for college student.,Great product.,1476316800,NaN,NaN,NaN
2,5.0,True,"11 21, 2015",A32RD6L701BIGP,4639725183,Krystal Clifton,"If you like strong tea, this is for you. It mi...",Strong,1448064000,NaN,NaN,NaN
3,5.0,True,"08 12, 2015",A2UY1O1FBGKIE6,4639725183,U. Kane,Love the tea. The flavor is way better than th...,Great tea,1439337600,NaN,NaN,NaN
4,5.0,True,"05 28, 2015",A3QHVBQYDV7Z6U,4639725183,The Nana,I have searched everywhere until I browsed Ama...,This is the tea I remembered!,1432771200,NaN,NaN,NaN

In [5]:
len(df.reviewerName.unique())

101478

In [4]:
df.isnull().sum()

overall                 0
verified                0
reviewTime              0
reviewerID              0
asin                    0
reviewerName          138
reviewText            390
summary               219
unixReviewTime          0
vote               985658
style              551774
image             1134350
dtype: int64

In [36]:
df2 = df.fillna({'reviewerName': 1111})                               # Fill empty values
# df3 = df2[~df2.reviewerName.str.match('1111')]        # Filter empty value rows  

if df.isnull().sum().reviewerName == (len(df2) - len(df3)):
    print ('We successfully filtered NA user row')
else:
    print ('Please check the logic')

We successfully filtered NA user row

In [6]:
len(df3.reviewerName.unique())

101477

In [39]:
df2.loc[df2['reviewerName'] == 1111]

,overall,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,unixReviewTime,vote,style,image
5399,5.0,True,"11 18, 2015",A2TCW7OML05YKB,B00012NHAC,1111,good,Five Stars,1447804800,NaN,"{'Size:': ' OG, ESSENTIAL GROUND, 15 OZ'}",NaN
13805,5.0,True,"08 28, 2015",ACBIWFCXC9H8A,B0001M10LU,1111,so good,Five Stars,1440720000,NaN,NaN,NaN
16079,4.0,True,"02 27, 2014",A1GXJW4152V4LJ,B0001LO3FG,1111,Last year I gave up all carbonated beverages a...,Excellent caffine free substitute,1393459200,17,"{'Size:': ' 20 Count (Pack of 6)', 'Flavor:': ...",NaN
25211,5.0,True,"08 10, 2014",A1F0YUBWGEOQBX,B00061EYPU,1111,:),Five Stars,1407628800,NaN,{'Size:': ' 1 PACK'},NaN
46797,4.0,False,"08 10, 2014",A1F0YUBWGEOQBX,B000CONMBS,1111,Hmm,Four Stars,1407628800,NaN,"{'Size:': ' 1-Ounce Bags (Pack of 24)', 'Flavo...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1090203,4.0,True,"08 16, 2014",A1CSE3HAJ983NJ,B00AF7LCRI,1111,Good bussiness n nice products. Not so good ab...,Nice.,1408147200,NaN,NaN,NaN
1091184,4.0,True,"05 4, 2018",A15KXWCBIRE8FU,B00ARH5GCS,1111,Only out once a year; a pleasure to consume,Yum,1525392000,NaN,NaN,NaN
1108794,5.0,True,"08 28, 2015",ACBIWFCXC9H8A,B000WS1KEU,1111,"very fresh, great taste!",great taste!,1440720000,NaN,NaN,NaN
1112529,5.0,True,"04 30, 2018",A15KXWCBIRE8FU,B00IH28XDE,1111,"There are rumours that MSG is bad for you, but...",Makes Stuff Good,1525046400,2,NaN,NaN
1134507,5.0,False,"10 11, 2015",A3GIWIJINP2T8D,B012HDK6WE,1111,This would be the very first time I ever opted...,"WOW, Juicy and Tender Steak!",1444521600,NaN,NaN,[https://images-na.ssl-images-amazon.com/image...

In [43]:
df_filtered = df2.loc[(df2['verified'] == True) & (df2['reviewerName'] != 1111)]

In [44]:
df_filtered.head()

,overall,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,unixReviewTime,vote,style,image
0,5.0,True,"11 19, 2014",A1QVBUH9E1V6I8,4639725183,Jamshed Mathur,No adverse comment.,Five Stars,1416355200,NaN,NaN,NaN
1,5.0,True,"10 13, 2016",A3GEOILWLK86XM,4639725183,itsjustme,Gift for college student.,Great product.,1476316800,NaN,NaN,NaN
2,5.0,True,"11 21, 2015",A32RD6L701BIGP,4639725183,Krystal Clifton,"If you like strong tea, this is for you. It mi...",Strong,1448064000,NaN,NaN,NaN
3,5.0,True,"08 12, 2015",A2UY1O1FBGKIE6,4639725183,U. Kane,Love the tea. The flavor is way better than th...,Great tea,1439337600,NaN,NaN,NaN
4,5.0,True,"05 28, 2015",A3QHVBQYDV7Z6U,4639725183,The Nana,I have searched everywhere until I browsed Ama...,This is the tea I remembered!,1432771200,NaN,NaN,NaN

In [45]:
len(df_filtered)

993735

In [47]:
len(df_filtered.asin.unique())

41087